# Generated by Django 6.0.1 on 2026-05-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('github', 'GitHub'), ('manual', 'Email/Password')], default='manual', help_text="Type de compte utilisé pour l'authentification", max_length=20)),
                ('avatar_url', models.URLField(blank=True, help_text='Avatar URL from social provider', null=True)),
                ('bio', models.TextField(blank=True, help_text='User bio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
