# Generated by Django 6.0.6 on 2026-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('technologies', models.JSONField(default=list)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('raw_headers', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Résultat de scan',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
